import { useTheme } from "next-themes";
import Head from "next/head";
import Image from "next/image";
import { MacTerminal } from "../components/MacTerminal";
import Navbar from "../components/Navbar";
import styles from "../styles/Home.module.css";
import HeroSection from "../components/HeroSection";

import "@fortawesome/fontawesome-free";
import { SkillsSection } from "../components/SkillsSection";

export default function Home() {
  const { theme, setTheme } = useTheme();

  return (
    <div>
      <Head>
        <title>halalsenpai</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <HeroSection />
      <SkillsSection />

      <main className={styles.main}></main>
    </div>
  );
}
