export default function Home() {
  return (
    <div>
      {/* <Head>
        <title>halalsenpai</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <HeroSection />
      <SkillsSection /> */}
      <main className="">Testing</main>
    </div>
  );
}
